# Fly.io Configuration for Financial Advisor App
# Optimized for Mumbai region deployment

app = "thegoldenpath"
primary_region = "sin"  # Singapore region (Mumbai unavailable)
kill_signal = "SIGTERM"
kill_timeout = 5

# Build configuration
[build]
  # Using Dockerfile for better control
  dockerfile = "Dockerfile"
  
  # Build arguments - hardcoded values needed for Next.js client-side access
  [build.args]
    NEXT_PUBLIC_ELEVENLABS_API_KEY = "sk_cd55b4880d52649ff1f9e68737288f8c1e561a841c10f5f6"
    NEXT_PUBLIC_ELEVENLABS_AGENT_ID = "agent_5101k23cnhj8ey5rj2g4b0vf76vb"

# Environment variables (non-sensitive)
[env]
  PORT = "3000"
  NODE_ENV = "production"
  # Database path for Fly.io volume
  DATABASE_PATH = "/data/database.sqlite"
  # Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"

# Experimental features for better performance
[experimental]
  auto_rollback = true

# HTTP service configuration
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
  # Concurrency limits
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

# Volume mount for SQLite database
[mounts]
  source = "sqlite_data"
  destination = "/data"

# Machine configuration
[[vm]]
  # Start with small instance, scale as needed
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Deploy configuration
[deploy]
  # Strategy for zero-downtime deployments
  strategy = "rolling"
  
  # Wait for health checks before considering deployment successful
  wait_timeout = "5m"