export interface Message {
  id: string;
  type?: 'user' | 'assistant'; // Make optional for compatibility
  sender?: 'user' | 'assistant'; // Keep for backward compatibility
  content: string;
  timestamp: Date;
  isVoice?: boolean;
  rawTranscript?: string; // Original voice transcript before cleanup
  citedArticles?: Article[]; // Add support for cited articles in RAG responses
}

export interface Session {
  id: string;
  title: string;
  messages: Message[];
  notes: SessionNote[];
  createdAt: Date;
  updatedAt: Date;
  summary?: string;
  isActive?: boolean; // Add missing field used in code
}

export interface SessionNote {
  id: string;
  content: string;
  type: 'insight' | 'action' | 'recommendation' | 'question';
  timestamp: Date;
  messageId?: string; // Link to the message that generated this note
  autoGenerated?: boolean; // Add missing field for auto-generated notes
  priority?: 'high' | 'medium' | 'low'; // Add priority field from CLAUDE.md
}

export interface Article {
  id: string;
  title: string;
  summary: string;
  content: string;
  category: string;
  tags: string[];
  readTime: string;
  author: string;
  lastUpdated: Date;
}

export interface VoiceRecording {
  isRecording: boolean;
  transcript: string;
  confidence?: number;
  error?: string;
}

export interface KnowledgeBaseContext {
  relevantArticles: Article[];
  searchQuery: string;
  confidence: number;
}